### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by jpopelka**
Usually typos and small rewordings.

### CODE REVIEW

**Comment by strzibny** [comment]
@asamalik We should probably talk about handling page renames (some moved permanently redirects on the site).

**Comment by jpopelka** [comment]
Should I split this PR into two ? One for the automake -> autotools and second for the rest ?

**Comment by phracek** [comment]
I vote for splitting. How will you do it?

**Comment by jpopelka** [comment]
Rebased and moved the renaming commit into #100

**Pull request merged**
