### PR TITLE
Mark Jython and Python 3.5 to be removed in Fedora 35

### PR DESCRIPTION
**Pull request by hroncok**
Related to https://github.com/developer-portal/content/issues/372

I've decided to keep the Jython info for the Fedora 34 release.

### CODE REVIEW

**Comment by pvalena** [comment]
Oh, ok. Does the `<sup>` work in jekyll? I can check later on...

**Comment by hroncok** [comment]
It works in mardkown.

 * Jython<sup>💀</sup>

**Comment by hroncok** [comment]
If you ship it and it breaks, we can revert it.

**Comment by pvalena** [comment]
Sure, we can check on staging.

**Comment by hroncok** [comment]
Can I merge this?

**Comment by pvalena** [comment]
Sure :).

I'll let you know when the staging is refreshed, and then you can check it and revert if needed ;).

**Pull request merged**
