### PR TITLE
C# pages: Added .NET Core stuff.

### PR DESCRIPTION
**Pull request by RheaAyase**
_(You can squash it into one if you want, it's all one big change...)_

### CODE REVIEW

**Comment by pvalena** [comment]
Why you've closed the #200 PR and created new- a very simillar one? You can always rebase/amend/reset/etc. on your branch/fork and the changes are reflected in the PR.

I think most of the comments from #200 are still valid. Please check those and squash those unnecessary commits etc.
Thanks!

**Comment by RheaAyase** [comment]
> Why you've closed the #200 PR and created new- a very simillar one? You can always rebase/amend/reset/etc.

And if I'll be fixing one more thing (see below) i'll close this and open a new one again. I don't have time to fiddle with shit for ages, I don't have a single minute to spare.

> I think most of the comments from #200 are still valid.

They are not. Neither my "code," nor my changes. All I can fix in the rest is the "absolute link" (which wasn't my commit either.)

> Please check those and squash those unnecessary commits etc.

Please squash it when merging, as there is a nice and easy way to do so with but a single press of a button.

**Comment by pvalena** [comment]
> And if I'll be fixing one more thing (see below) i'll close this and open a new one again. I don't have time to fiddle with shit for ages, I don't have a single minute to spare.

My time is valuable and indispensable too and you are wasting it by useless reviews. You should learn how to use git (and github), because closing and opening PRs is absolutely unnecessary, as github changes the PR for you with you changing the content on respective branch/fork.

> They are not. Neither my "code," nor my changes. All I can fix in the rest is the "absolute link" (which wasn't my commit either.)

It's your PR and therefore 'your commits'. You can simply: edit; squash; reword, rebase; or [reset](https://git-scm.com/docs/git-reset) and group changes into meaningful packs which we call commits. This PR is a mess: commits fixing your other commits; commits bearing unrelevant messages; merge commits. You have to fix those before I accept this PR.

If you do not want edit "other people's" commits, then let those people create separate PRs.

> Please squash it when merging, as there is a nice and easy way to do so with but a single press of a button.

I am not accepting one big commit with all changes in one when it does not make sense. Nor I am accepting numerous commits unrelevant to the change you're proposing(f.e. "Caught them bugs."). What I see from brief look are at least two commits.

On top of that squashing on merge is disabled in this repo. It's up to you to fix those issues. It's [pretty easy](http://rogerdudler.github.io/git-guide/) in git.

**Comment by RheaAyase** [comment]
> My time is valuable and indispensable too and you are wasting it by useless reviews.

It's about you choosing an option to "squash and merge" instead of "merge" which is literally single mouse click away. Squashing it manually on my end is a lot of work. So to sum this up, zero time wasted on your end, 15 minutes on mine?

> I am not accepting one big commit with all changes in one when it does not make sense.

Oh yes, it does make sense. The pages are called `C#` and therefor it should contain the info about C# (relevant to Fedora) and not only mono. Therefor it's one single change, an update to the page, to pull it out of early 2000s into 2015-2017.

> It's pretty easy in git.

It's a lot of copypasting and fiddling with it, which I wanted to avoid doing - waste of time for nothing, other than cleaner looking commits... No changes to the content, pointless work.

> This PR is a mess

This is what any and every work looks like. You do something one day, commit your work, get back to it the next day, commit more, etc... I was hoping that we are a bit more friendly here to not insist on bureaucratic nonsense. Have it your way. (I'll still submit a new PR.)

---

Guess why did it take close to two weeks to even reply, yet to actually do something? I'm [pretty busy](http://i.imgur.com/cWDK38L.png) (FYI that tutorial of yours is for basic stuff, I highly doubt that it's talking about rebasing. All it achieved is insult me.)

**Comment by pvalena** [comment]
Are you sure you want to get into a pointless discussion? I was trying to explain stuff to you, that you obviously do not understand and you only try to argue your way out instead of reading properly.

Thus I will reply as briefly as possible:

> It's about you choosing an option to "squash and merge" instead of "merge" which is literally single mouse click away. Squashing it manually on my end is a lot of work. So to sum this up, zero time wasted on your end, 15 minutes on mine?

No and no. Should be max. 2 minutes on your side. See what I've written above(reset was the key word).
Anyway, like I said, squashing on merge is **disabled** in this repo, so resistance is futile.

> Oh yes, it does make sense. The pages are called C# and therefor it should contain the info about C# (relevant to Fedora) and not only mono. Therefor it's one single change, an update to the page, to pull it out of early 2000s into 2015-2017.

[Nope](https://sethrobertson.github.io/GitBestPractices/#sausage). 

> It's a lot of copypasting and fiddling with it, which I wanted to avoid doing - waste of time for nothing, other than cleaner looking commits... No changes to the content, pointless work.

Bad workflow, bad technique. 2 git commands. 30 seconds. And I also had some comments to the content, so If you did not fix those....

> This is what any and every work looks like. You do something one day, commit your work, get back to it the next day, commit more, etc... I was hoping that we are a bit more friendly here to not insist on bureaucratic nonsense. Have it your way. (I'll still submit a new PR.)

Again: bad workflow and also useless work by creating a new PR. Oh, if you only did read what I've written so you could see that creating new PR is completely avoidable and quite stupid IMHO.

> Guess why did it take close to two weeks to even reply, yet to actually do something? I'm pretty busy (FYI that tutorial of yours is for basic stuff, I highly doubt that it's talking about rebasing. All it achieved is insult me.)

Well If maybe try to learn to work in a more effective manner...
FYI: Yeah, you have to start with the basic stuff. It should quite cover your needs in this simple case as you do not need to rebase(at least for now).

**Comment by RheaAyase** [comment]
> Bad workflow, bad technique. 2 git commands. 30 seconds. And I also had some comments to the content, so If you did not fix those....

> FYI: Yeah, you have to start with the basic stuff. It should quite cover your needs in this simple case as you do not need to rebase(at least for now).

It was more than 2 git commands and 30 seconds to write new commit messages. And please excuse my lack of git experience as my professional history was full of Perforce and other enterprise project management stuff instead. I do not know any other way to squash commits than git rebase.

And thank you for more insults, next time you could try walking over to my desk (FBC-II - 2np - Bridge 2S327) to insult me in the face, so it's more classy.

> Again: bad workflow and also useless work by creating a new PR. Oh, if you only did read what I've written so you could see that creating new PR is completely avoidable and quite stupid IMHO.

I'e never created or changed PR via commandline so it would be much more time wasted on my end. Again, just because you don't understand different workflow of different people with different professional background, **does not give you right to insult them.** You should try to give people the benefit of doubt, trust in their good intentions, and respect them by default.

This was two button clicks. "commend & close" here, and "create PR" back in the repo with pasting the title andhitting submit. So much easier than figuring out how to edit PR - don't you think?

---

Take the new PR or leave it. I'm done here.

**Comment by pvalena** [comment]
> It was more than 2 git commands and 30 seconds to write new commit messages. And please excuse my lack of git experience as my professional history was full of Perforce and other enterprise project management stuff instead. I do not know any other way to squash commits than git rebase.

Obviously, I cannot judge, and I do not try to, any experience of yours and I am sorry you're offended by me forcing you write proper commit messages and giving you recommendations for the means. 

> And thank you for more insults, next time you could try walking over to my desk (FBC-II - 2np - Bridge 2S327) to insult me in the face, so it's more classy.

No need for that. Also if you accept recommendation and facts as insults there would be no point comming there, as I had no other intentions than helping you stop wasting time of yours(and mine).
I hope you know where to find me in case you need to relief your anger(I do not hold grudges so you're free to do so).

> I'e never created or changed PR via commandline so it would be much more time wasted on my end. Again, just because you don't understand different workflow of different people with different professional background, does not give you right to insult them. You should try to give people the benefit of doubt, trust in their good intentions, and respect them by default.

You're free to use any means that suite you. All I did was to suggest a better way(generally accepted), as you seemed troubled with my 'requests'. 

> , and respect them by default.

Seems strange reading this [from you](https://github.com/developer-portal/content/pull/201#issuecomment-306455977).
Anyway, your contributions are still welcome, as long as they're in acceptable format.

> This was two button clicks. "commend & close" here, and "create PR" back in the repo with pasting the title andhitting submit. So much easier than figuring out how to edit PR - don't you think?

I think all me collegues would agree with me when I say: No. For reasons I gave to you previously.

**Comment by RheaAyase** [comment]
As I said, take it or leave it. I have deadlines for several unrelated products to attend to and my 12h/day work is not gonna be enough. Good bye.

**Comment by strzibny** [comment]
> As I said, take it or leave it. 

Seriously cannot believe this discussions, @RheaAyase. And you are even a community manager? We certainly do not accept PRs based on explanations such as *I have deadlines for several unrelated products*.

@pvalena I suggest we lock this conversation and abandon this PRs until someone else picks up on them.

**Comment by RheaAyase** [comment]
@strzibny 
The take it or leave it is for #205 FYI. I said that i'll be fixing it and submitting new PR. Take the new one, or leave it. This one was closed ages ago.

> And you are even a community manager?

Are you even human? I now deeply regret that I was naive enough to think that we are friends here and that I don't have to treat this as overly serious repository. I am sorry for thinking that you would help me out a little with not insisting on bureaucracy. In the end, I had to do it your way, and you still complain?

**Comment by strzibny** [comment]
I was just shocked by your communication since @pvalena definitely tried to help you here and I would gladly help you too. I commented because I had a notification, did not realize there is a new PR already (and 5 days is **not** ages ago).

> naive enough to think that we are friends here and that I don't have to treat this as overly serious repository

We are software maintainers and developers here and try to keep the repository nice. We help those that don't know how to use `git` or are confused how Jekyll works -- as long as there are willing to learn and try. Being a friend is not an excuse to accept half baked work.

**Pull request closed without merging**
