### PR TITLE
Documentation of how to package Desktop applications

### PR DESCRIPTION
**Pull request by cschalle**
Hi,
Here is the long promised and discussed document outlining rules and suggestions for packaging desktop application for Fedora Workstation. I haven't linked to it from anything as I wasn't sure I was supposed to edit existing pages.

### CODE REVIEW

**Comment by pvalena** [comment]
@cschalle thanks for your contribution!

> I haven't linked to it from anything as I wasn't sure I was supposed to edit existing pages.

You are free to edit anything as long as it makes sense ;) this is an opensourced web.
Just use separate commits.

**Comment by pvalena** [comment]
Please squash this: `Merge pull request #2 from matthiasclasen/small-fixes`

IOW use rebase and merge (or fast-forward) instead of adding a merge commit.

**Comment by pvalena** [comment]
Please also give some proper name to commit `More cosmetics` especially when adding new content(I've seen some AFAIK). Use `language corrections` or preferably/possible do not use any separate commit for that, as you can rebase your own PR freely. Feel free to contact me on #developer-portal @ Freenode with any questions.

**Comment by cschalle** [comment]
Updated repository based on feedback

**Comment by pvalena** [comment]
I have checked your changes and it seems you're using your absolute paths of your OS for images inclusion:
```
/home/cschalle/Pictures/steam-gnome-software.png
```

Please change the links similarly to [micropython.md](https://github.com/developer-portal/content/blob/master/tech/languages/python/micropython.md). You also need to include a header similar to `micropython.md` one.

I was also thinking a section in 'Deploy and distribute' would be more suitable to cover this topic. Possibly as a subsection of [RPM](https://developer.fedoraproject.org/deployment/rpm/about.html) or a standalone section, with content split to subsections, because of your broad topic coverage. 

Please do a rebase and use commit message simillar to `Add "How to package gui application" subsection`, since you are making no other changes AFAICT. You can use this sequence of commands in your git repository to rebase, include your changes and to change the commit the message:

```
MSG='COMMIT MESSAGE'
(
set -xe
git remote add upstream git://github.com/developer-portal/content.git
git fetch upstream
git stash
git reset 'HEAD^'
git stash
git reset --hard upstream/master
git stash apply
git add start/sw/gui-app/{example-gnome-software-listing.png,steam-gnome-software.png,how-to-package-a-desktop-application.md}
git commit -m "$MSG"
set +xe
)
```
You can run this(including the brackets) all at once, or alternatively one by one, but without the set commands.

The copyright you have included on top of the page is also not suitable, because the web is under [GPL License](https://github.com/developer-portal/content/blob/master/LICENSE) and on bottom of every page there is stated copyright `© 2017 Red Hat, Inc. and others.`. I would have to contact legal if it's possible to include your copyright.

Please also note that this web page is not intended for documentation itself, but merely for a `quick start guide`, `specific developer setup/configuration`, and other similar types of content. Therefore your content as it is should be IMHO refused, but I think it's possible to convert it into some form more suitable for our audience.

Do not forget to check our [contribution guide](http://developer-portal.github.io/contributing/write-introduction.html), which covers most of the above topics.
You are also very welcome to join [our ML](https://lists.fedoraproject.org/archives/list/developer-portal@lists.fedoraproject.org/) and ask any questions there.

**Comment by cschalle** [comment]
Ok, I think I fixed the issues mentioned. I would like to not change the
format to much as the primary target audience is 3rd parties wanting to
target Fedora and thus I would like it to be a 1 stop document for them.

Christian

**Comment by pvalena** [comment]
I am afraid the mentioned issues are not fixed. See https://github.com/developer-portal/content/issues/199.

**Comment by cschalle** [comment]
Hi Pavel,
Ok, tried cleaning up again and I ended up deleting my original repository
fork to create a clean history commit. This should be done now.  Since the
images are in the same directory as the md file the paths should now also
be correct and copyright notice removed. As for the final destination of
the tutorial on the website I don't have a strong preference, so if you
want to move it to a different section that is fine by me. Let me know if I
need to create a new pull request since the original cloned repo got
deleted.

Sincerely,
Christian Schaller

**Comment by pvalena** [comment]
Hi,
> Ok, tried cleaning up again and I ended up deleting my original repository fork to create a clean history commit. This should be done now. 

Yes, it is removed, and you have a clean commit history. (You could use the script I wrote for you above to achieve the same result while preserving this PR and your repo.)

>  Let me know if I need to create a new pull request since the original cloned repo got deleted.

Yes, please do create a new PR (this one is not connected to your repository anymore).

>  As for the final destination of the tutorial on the website I don't have a strong preference, so if you
want to move it to a different section that is fine by me.

Yes, please do move the page to a new subsection in [Deploy and Distribute](https://developer.fedoraproject.org/deployment.html) section and split your content into multiple pages. Do not forget to add [jekyll headers](http://developer-portal.github.io/doc/file-structure.html) to all you pages, otherwise they will not be accessible on the web.

You also do have some [merge artefacts](https://github.com/cschalle/content/commit/bef92b74f6478c1a9f6b12fa7c238c5ddc1a6792#diff-a82fc82fb1c05da522a3bad7b2563955R45) in your code.

HIH,
Pavel

**Pull request closed without merging**
