### PR TITLE
Update `virt-builder` subsection

### PR DESCRIPTION
**Pull request by kashyapc**
- Remove examples of old Fedora releases
 - Describe a bit about "--os-variant"
 - Some minor wording tweaks

Signed-off-by: Kashyap Chamarthy <kchamart@redhat.com>

### CODE REVIEW

**Comment by pvalena** [comment]
Please use `git reset --hard <commit>` next time instead, as it achieves the same result.
There is really [no need](https://github.com/developer-portal/content/pull/236#issuecomment-360588687) to delete the fork and lose track of the changes made.

I will review this next month. Website update was released last week.

**Comment by kashyapc** [comment]
Yeah, I should've used `git reset --hard`. I was in a hurry with something else, and did the crudest thing possible as I had the patch file (generated via `git format-patch -M -C --patience --full-index -1`), and I simply applied it. But agree with you in principle.

**Comment by pvalena** [comment]
_[OT] Alternatively, you can use `git stash` to save the changes you're interested in saving specific changes (you have to soft reset the commits first)._

**Comment by pvalena** [comment]
LGTM.
Thanks!

**Pull request merged**
