### PR TITLE
Modernize python tutorials and add info about venv.

### PR DESCRIPTION
**Pull request by Krejdom**
Hi,
I've improved Python tutorials:

- Add info about virtual environments.
- Show how easy is to use Python stuff.
- Delete obsolete things like bpython.
- Use just Python 3.

### CODE REVIEW

**Comment by hroncok** [comment]
JFYI This has been done with in coordination with @fedora-python.

**Comment by pvalena** [comment]
Is it a bad idea to install `python3-django` from Fedora or to mention this option?

**Comment by hroncok** [comment]
You can install that from Fedora when running a server. But when
developing, installing to virtualenv gives you more flexibility and most
Python developers in the wild will do it that way.

Dne 5. 12. 2016 15:00 napsal uživatel "Pavel Valena" <
notifications@github.com>:

**Comment by hroncok** [comment]
"You can create virtualenvs and pip install stuff inside out of the box" is much cooler than "If you want to develop Django apps, install a frozen version of Django form RPM and hope other libraries you need will be there as well"

**Comment by pvalena** [comment]
Please consider adding `Deployment from virtual environment` (or alike) subsection.

**Comment by pvalena** [comment]
You can check your changes prior to release here:
http://developer.fedorainfracloud.org/tech/languages/python/django-installation.html
http://developer.fedorainfracloud.org/tech/languages/python/flask-installation.html
http://developer.fedorainfracloud.org/tech/languages/python/pypi-installation.html
http://developer.fedorainfracloud.org/tech/languages/python/python-installation.html

**Comment by hroncok** [comment]
Thanks. Any chance we could see this, #162 and #166 deployed to the main website before release party in Brno (a.k.a. today)?

**Comment by asamalik** [comment]
@pvalena could we do that? I think it would be great to have it there.

**Comment by pvalena** [comment]
Sure, @asamalik and @hroncok, I am working on staging version now.

**Pull request merged**
