### PR TITLE
tools: Add virt-builder

### PR DESCRIPTION
**Pull request by kashyapc**
`virt-builder`[1] is a tool that allows you to quickly build (and
customize) virtual machine disk images.

[1] http://libguestfs.org/virt-builder.1.html

### CODE REVIEW

**Comment by phracek** [comment]
Great. Could you please modify it for Fedora 23?

I will go through it and review it.

**Comment by kashyapc** [comment]
I intentionally didn't add for Fedora 23, as the `virt-builder` image for F23 was only created _after_ I submitted this pull request. And, planned to submit one for Fedora 23 as an update later. Will update to F23.

I'm also trying to submit a pull request to add styling changes (libguestfs log, etc) to the 'website' Git repository, hitting some errors there. Will try to resolve and submit it too.

**Comment by kashyapc** [comment]
Err, I made a mistake by pushing my update by making the Git commit message same as the old one :-(.  I'll probably  abandon this pull request, and create a new pull request.

**Comment by kashyapc** [comment]
Here's the updated pull request with Fedora 23: https://github.com/developer-portal/content/pull/92

**Pull request closed without merging**
