### PR TITLE
mongodb-4.4.8.el8 has broken dependencies - MongoDB doesn't offer pac…

### PR DESCRIPTION
**Pull request by ben467834**
…kage support for Fedora

When installing mongodb-org on Fedora 34
Installing:
 mongodb-org                                          x86_64                     4.4.4-1.el8                            mongodb-4.4                      10 k
Installing dependencies:
 cyrus-sasl                                           x86_64                     2.1.27-8.fc34                          fedora                           69 k
 fontconfig                                           x86_64                     2.13.94-2.fc34                         updates                         273 k
 libX11                                               x86_64                     1.7.2-3.fc34                           updates                         646 k
 libX11-common                                        noarch                     1.7.2-3.fc34                           updates                         152 k
 libXau                                               x86_64                     1.0.9-6.fc34                           fedora                           31 k
 libXft                                               x86_64                     2.3.3-6.fc34                           fedora                           63 k
 libXrender                                           x86_64                     0.9.10-14.fc34                         fedora                           27 k
 libxcb                                               x86_64                     1.13.1-7.fc34                          fedora                          230 k
 mongodb-database-tools                               x86_64                     100.5.0-1                              mongodb-4.4                      47 M
 mongodb-org-mongos                                   x86_64                     4.4.4-1.el8                            mongodb-4.4                      22 M
 mongodb-org-tools                                    x86_64                     4.4.4-1.el8                            mongodb-4.4                      10 k
 python2.7                                            x86_64                     2.7.18-11.fc34                         updates                          13 M
 tix                                                  x86_64                     1:8.4.3-31.fc34                        fedora                          247 k
 tk                                                   x86_64                     1:8.6.10-6.fc34                        fedora                          1.6 M
 xml-common                                           noarch                     0.6.3-56.fc34                          fedora                           31 k
Downgrading:
 mongodb-org-server                                   x86_64                     4.4.4-1.el8                            mongodb-4.4                      28 M
 mongodb-org-shell                                    x86_64                     4.4.4-1.el8                            mongodb-4.4                      18 M
Skipping packages with broken dependencies:
 mongodb-org                                          x86_64                     4.4.8-1.el8                            mongodb-4.4                      11 k
 mongodb-org-database-tools-extra                     x86_64                     4.4.8-1.el8                            mongodb-4.4                      23 k
 mongodb-org-tools                                    x86_64                     4.4.8-1.el8                            mongodb-4.4                      11 k

### CODE REVIEW

**Comment by pvalena** [comment]
Is there some workaround for this? Adding a reference to the ticket just says it's broken, but it should be ideally fixed instead ;).

**Comment by ben467834** [comment]
Unfortunately the alternative repo hosted by amazon also doesn't work: https://stackoverflow.com/questions/68617654/error-problem-nothing-provides-usr-libexec-platform-python-needed-by-mongodb

Do you have a suggestion on how to fix the root cause (The mongo team does not support packaging for Fedora)?

**Comment by ben467834** [comment]
Just came across this for an older version. https://fedoramagazine.org/how-to-get-mongodb-server-on-fedora/

**Comment by jackorp** [comment]
> Do you have a suggestion on how to fix the root cause (The mongo team does not support packaging for Fedora)?

Building it yourself from the source or installing it forcefully using RPM `rpm --nodeps -ivh <mongodb package>` to get around the `nothing provides /usr/libexec/platform-python` if you really want it on a Fedora Linux system, however, then the person needs to install dependencies manually, and the compatibility may be shaky anyway in that case.

Or using containers (for example, with CentOS/RHEL 8), but maybe not suitable for Fedora Developer Portal, as the "Languages & Databases" sections should ideally showcase technology available on Fedora.

**Pull request closed without merging**
