### PR TITLE
Add sphinx artictle

### PR DESCRIPTION
**Pull request by FrostyX**
This PR adds content of #97 
Can we please discuss whether you consider it useful, and what should be improved?

Also, I would like to add image there, to let users see, what result they can expect. Please see #99.

### CODE REVIEW

**Comment by phracek** [comment]
@FrostyX Could you please update this PR? I don't see updates which are mentioned in What's next.
Could you please do it? Or shall I do it?

**Comment by FrostyX** [comment]
@phracek As I said before

> My apologies, but I can't see a difference between actual and suggested link (same for examples link above)

**Comment by phracek** [comment]
I will do fixes.

**Comment by FrostyX** [comment]
Thank you for merging! :-)

**Pull request merged**
