### PR TITLE
*csharp: Added vscode extension license.

### PR DESCRIPTION
**Pull request by RheaAyase**

### CODE REVIEW

**Comment by pvalena** [comment]
Please check http://developer.fedorainfracloud.org if that's an expected result (in 10minutes).

**Comment by RheaAyase** [comment]
> Please check http://developer.fedorainfracloud.org if that's an expected result (in 10minutes).

seems like it is, but still without the [website pr](https://github.com/developer-portal/website/pull/63)

**Comment by pvalena** [comment]
Anything merged should be pulled immediately, anyways, there's easy way to check:
https://github.com/developer-portal/developer.fedoraproject.org/commits/devel
 - this is what got actually pushed to devel instance.

**Comment by pvalena** [comment]
Note the commit message with website commit 1b05d73, which is the last one.

**Comment by RheaAyase** [comment]
I see nevermind, it wasn't merged yet... I got confused.

**Pull request merged**
