### PR TITLE
Python 2.6/tox: Add workaround with pip commands

### PR DESCRIPTION
**Pull request by tyll**

### CODE REVIEW

**Comment by pvalena** [comment]
@hroncok PTAL.

**Comment by pvalena** [comment]
Thanks, it LGTM.

**Comment by hroncok** [comment]
It looks good, but it makes https://github.com/developer-portal/content/issues/293 worse.

**Comment by tyll** [comment]
> It looks good, but it makes #293 worse.

the changes from this PR can easily be migrated with the other code when someone fixes #293.

**Comment by hroncok** [comment]
yes

**Comment by pvalena** [comment]
Ok, let's resolve the longeviness in the long run :)

Thanks for your PR!

**Pull request merged**
