### PR TITLE
Add tech/database/Cassandra content

### PR DESCRIPTION
**Pull request by caringi**

### CODE REVIEW

**Comment by pvalena** [comment]
Wow, that's a bit long. Have you considered splitting it into multiple files?

Sorry for answering so late.

**Comment by pvalena** [comment]
Any news on this? I do really think it should be split into multiple files, see, f.e.:

 [go](https://developer.fedoraproject.org/tech/languages/go/go-installation.html) - [source](https://github.com/developer-portal/content/tree/master/tech/languages/go)
 [ruby](https://developer.fedoraproject.org/tech/languages/ruby/ruby-installation.html) - [source](https://github.com/developer-portal/content/tree/master/tech/languages/ruby)

**Comment by caringi** [comment]
@pvalena I agree with you... I'll take a look into this soon!

**Comment by pvalena** [comment]
@caringi, thanks!

**Comment by pvalena** [comment]
Lets merge this and follow up with changes later.
Thanks!

**Pull request merged**
