### PR TITLE
Create gnome-builder.md

### PR DESCRIPTION
**Pull request by phracek**
Needs to be reviewed and added more templatest.

### CODE REVIEW

**Comment by kvok** [comment]
It should be clear the GNOME Software means the app. There may exist a website called like that and that would be confusing.
"or find **Builder** in the GNOME Software app" would be more suitable.

**Comment by phracek** [comment]
@kvok Can you please do a modification?

**Comment by phracek** [comment]
The issue was done from scratch and I don't thing that it is useful for Portal at all.

**Comment by felipeborges** [comment]
I would suggest placing the gnome-builder article within the tools section. It could be later linked in the gui-app section as well as in the language pages where using Builder as IDE is convenient (such as: C + Gtk+, Vala, PyGObject...)

**Pull request closed without merging**
